name       : haskell-quickcheck-io
version    : 0.2.0
release    : 3
source     :
    - https://hackage.haskell.org/package/quickcheck-io-0.2.0/quickcheck-io-0.2.0.tar.gz : fb779119d79fe08ff4d502fb6869a70c9a8d5fd8ae0959f605c3c937efd96422
license    : MIT
component  : programming.haskell
summary    : This package provides an orphan instance that allows you to use HUnit assertions as QuickCheck properties.
description: |
    This package provides an orphan instance that allows you to use HUnit assertions as QuickCheck properties.
builddeps  :
    - haskell-cabal-install
    - haskell-HUnit-devel
    - haskell-QuickCheck-devel
rundeps    :
    - devel:
        - haskell-HUnit-devel
        - haskell-QuickCheck-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
