name       : haskell-quickcheck-io
version    : 0.1.4
release    : 1
source     :
    - http://hackage.haskell.org/package/quickcheck-io-0.1.4/quickcheck-io-0.1.4.tar.gz : 6b3750590871b03908530764cdaa69ce67d5b514f533c1a4a6f4755f8267389d
license    : MIT
component  : programming.haskell
summary    : This package provides an orphan instance that allows you to use HUnit assertions as QuickCheck properties. 
description: |
    This package provides an orphan instance that allows you to use HUnit assertions as QuickCheck properties. 
builddeps  :
    - haskell-cabal-install
    - haskell-HUnit
    - haskell-QuickCheck
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
